# Generated by Django 3.2.21 on 2023-09-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fimsapp', '0002_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='maincardslider',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Main Card Sliders'},
        ),
        migrations.AlterModelOptions(
            name='patienttestimonial',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Patient Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Why Choose Us'},
        ),
    ]
