# Generated by Django 3.2.21 on 2023-09-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fimsapp', '0003_auto_20230906_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(upload_to='service'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='image',
            field=models.FileField(upload_to='statistics'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='image',
            field=models.FileField(upload_to='whychooseus'),
        ),
    ]
