# Generated by Django 3.2.21 on 2023-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fimsapp', '0005_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
